src/Entity/Dossier.php
<?php

namespace App\Entity;

use App\Repository\DossierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DossierRepository::class)]
class Dossier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'dossiers')]
    private ?Patient $patient = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_dossier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\OneToMany(mappedBy: 'dossier', targetEntity: Fiche::class)]
    private Collection $fiches;

    #[ORM\Column(length: 255)]
    private ?string $numero = null;

    public function __construct()
    {
        $this->fiches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getDescriptionDossier(): ?string
    {
        return $this->description_dossier;
    }

    public function setDescriptionDossier(string $description_dossier): static
    {
        $this->description_dossier = $description_dossier;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, Fiche>
     */
    public function getFiches(): Collection
    {
        return $this->fiches;
    }

    public function addFich(Fiche $fich): static
    {
        if (!$this->fiches->contains($fich)) {
            $this->fiches->add($fich);
            $fich->setDossier($this);
        }

        return $this;
    }

    public function removeFich(Fiche $fich): static
    {
        if ($this->fiches->removeElement($fich)) {
            // set the owning side to null (unless already changed)
            if ($fich->getDossier() === $this) {
                $fich->setDossier(null);
            }
        }

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function __toString()
    {
        return $this->numero;
    }
}

src/Entity/Examen.php
<?php

namespace App\Entity;

use App\Repository\ExamenRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExamenRepository::class)]
class Examen
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_examen = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_examen = null;

    #[ORM\ManyToOne(inversedBy: 'examens')]
    private ?Personnel $personnel = null;

    #[ORM\ManyToOne(inversedBy: 'examens')]
    private ?Patient $patient = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_examen = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomExamen(): ?string
    {
        return $this->nom_examen;
    }

    public function setNomExamen(string $nom_examen): static
    {
        $this->nom_examen = $nom_examen;

        return $this;
    }

    public function getDescriptionExamen(): ?string
    {
        return $this->description_examen;
    }

    public function setDescriptionExamen(string $description_examen): static
    {
        $this->description_examen = $description_examen;

        return $this;
    }

    public function getPersonnel(): ?Personnel
    {
        return $this->personnel;
    }

    public function setPersonnel(?Personnel $personnel): static
    {
        $this->personnel = $personnel;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getDateExamen(): ?\DateTimeInterface
    {
        return $this->date_examen;
    }

    public function setDateExamen(\DateTimeInterface $date_examen): static
    {
        $this->date_examen = $date_examen;

        return $this;
    }
}

src/Entity/Patient.php
<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\DBAL\Types\Types;

#[ORM\Entity(repositoryClass: PatientRepository::class)]
class Patient implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_patient = null;

    #[ORM\Column(length: 255)]
    private ?string $postnom_patient = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_patient = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_patient = null;

    #[ORM\Column]
    private ?int $age = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $matricule = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\ManyToOne(inversedBy: 'patients')]
    private ?Personnel $personnel = null;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: Dossier::class)]
    private Collection $dossiers;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: Diagnostic::class)]
    private Collection $diagnostics;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: Examen::class)]
    private Collection $examens;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: Ordonnance::class)]
    private Collection $ordonnances;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: Fiche::class)]
    private Collection $fiches;

    #[ORM\OneToMany(mappedBy: 'patient', targetEntity: Signalement::class)]
    private Collection $signalements;

    public function __construct()
    {
        $this->dossiers = new ArrayCollection();
        $this->diagnostics = new ArrayCollection();
        $this->examens = new ArrayCollection();
        $this->signals = new ArrayCollection();
        $this->ordonnances = new ArrayCollection();
        $this->fiches = new ArrayCollection();
        $this->signalements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNomPatient(): ?string
    {
        return $this->nom_patient;
    }

    public function setNomPatient(string $nom_patient): static
    {
        $this->nom_patient = $nom_patient;

        return $this;
    }

    public function getPostnomPatient(): ?string
    {
        return $this->postnom_patient;
    }

    public function setPostnomPatient(string $postnom_patient): static
    {
        $this->postnom_patient = $postnom_patient;

        return $this;
    }

    public function getPrenomPatient(): ?string
    {
        return $this->prenom_patient;
    }

    public function setPrenomPatient(string $prenom_patient): static
    {
        $this->prenom_patient = $prenom_patient;

        return $this;
    }

    public function getDescriptionPatient(): ?string
    {
        return $this->description_patient;
    }

    public function setDescriptionPatient(string $description_patient): static
    {
        $this->description_patient = $description_patient;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): static
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getPersonnel(): ?Personnel
    {
        return $this->personnel;
    }

    public function setPersonnel(?Personnel $personnel): static
    {
        $this->personnel = $personnel;

        return $this;
    }

    /**
     * @return Collection<int, Dossier>
     */
    public function getDossiers(): Collection
    {
        return $this->dossiers;
    }

    public function addDossier(Dossier $dossier): static
    {
        if (!$this->dossiers->contains($dossier)) {
            $this->dossiers->add($dossier);
            $dossier->setPatient($this);
        }

        return $this;
    }

    public function removeDossier(Dossier $dossier): static
    {
        if ($this->dossiers->removeElement($dossier)) {
            // set the owning side to null (unless already changed)
            if ($dossier->getPatient() === $this) {
                $dossier->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Diagnostic>
     */
    public function getDiagnostics(): Collection
    {
        return $this->diagnostics;
    }

    public function addDiagnostic(Diagnostic $diagnostic): static
    {
        if (!$this->diagnostics->contains($diagnostic)) {
            $this->diagnostics->add($diagnostic);
            $diagnostic->setPatient($this);
        }

        return $this;
    }

    public function removeDiagnostic(Diagnostic $diagnostic): static
    {
        if ($this->diagnostics->removeElement($diagnostic)) {
            // set the owning side to null (unless already changed)
            if ($diagnostic->getPatient() === $this) {
                $diagnostic->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Examen>
     */
    public function getExamens(): Collection
    {
        return $this->examens;
    }

    public function addExamen(Examen $examen): static
    {
        if (!$this->examens->contains($examen)) {
            $this->examens->add($examen);
            $examen->setPatient($this);
        }

        return $this;
    }

    public function removeExamen(Examen $examen): static
    {
        if ($this->examens->removeElement($examen)) {
            // set the owning side to null (unless already changed)
            if ($examen->getPatient() === $this) {
                $examen->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ordonnance>
     */
    public function getOrdonnances(): Collection
    {
        return $this->ordonnances;
    }

    public function addOrdonnance(Ordonnance $ordonnance): static
    {
        if (!$this->ordonnances->contains($ordonnance)) {
            $this->ordonnances->add($ordonnance);
            $ordonnance->setPatient($this);
        }

        return $this;
    }

    public function removeOrdonnance(Ordonnance $ordonnance): static
    {
        if ($this->ordonnances->removeElement($ordonnance)) {
            // set the owning side to null (unless already changed)
            if ($ordonnance->getPatient() === $this) {
                $ordonnance->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Fiche>
     */
    public function getFiches(): Collection
    {
        return $this->fiches;
    }

    public function addFich(Fiche $fich): static
    {
        if (!$this->fiches->contains($fich)) {
            $this->fiches->add($fich);
            $fich->setPatient($this);
        }

        return $this;
    }

    public function removeFich(Fiche $fich): static
    {
        if ($this->fiches->removeElement($fich)) {
            // set the owning side to null (unless already changed)
            if ($fich->getPatient() === $this) {
                $fich->setPatient(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom_patient . " " . $this->postnom_patient . " " . $this->prenom_patient;
    }

    /**
     * @return Collection<int, Signalement>
     */

src/Entity/Signal.php
<?php

namespace App\Entity;

use App\Repository\SignalRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SignalRepository::class)]
class Signal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'signals')]
    private ?Patient $patient = null;

    #[ORM\ManyToOne(inversedBy: 'signals')]
    private ?Personnel $personnel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $observation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_signal = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getPersonnel(): ?Personnel
    {
        return $this->personnel;
    }

    public function setPersonnel(?Personnel $personnel): static
    {
        $this->personnel = $personnel;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(string $observation): static
    {
        $this->observation = $observation;

        return $this;
    }

    public function getDateSignal(): ?\DateTimeInterface
    {
        return $this->date_signal;
    }

    public function setDateSignal(\DateTimeInterface $date_signal): static
    {
        $this->date_signal = $date_signal;

        return $this;
    }
}

templates/patient/details_patient.html.twig
{% extends 'patient_template.html.twig' %}

{% block title %} AlloDocteur - Détails patient {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Patient {{ patient.nomPatient }}</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Nom patient : {{ patient.nomPatient }}</h5><br>
                                <h5>Post-nom patient : {{ patient.postnomPatient }}</h5><br>
                                <h5>Prenom patient : {{ patient.prenomPatient }}</h5><br>
                                <h5>Description du patient : {{ patient.descriptionPatient }}</h5><br>
                                <h5>Age patient : {{ patient.age }} ans</h5><br>
                                <h5>Numéro de téléphone : {{ patient.telephone }}</h5><br>
                                <h5>Matricule : {{ patient.matricule }}</h5><br>
                                <h5>Médecin traitent : {{ patient.personnel }}</h5><br>
                                <h5>Date de création : {{ patient.dateCreation|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}

templates/patient/details_personnel.html.twig
{% extends 'patient_template.html.twig' %}

{% block title %} AlloDocteur - Details Personnel {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Personnel</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Nom personnel : {{ personnel.nomPersonnel }}</h5><br>
                                <h5>Post-nom personnel : {{ personnel.postnomPersonnel }}</h5><br>
                                <h5>Prenom personnel : {{ personnel.prenomPersonnel }}</h5><br>
                                <h5>Description du personnel : {{ personnel.descriptionPersonnel }}</h5><br>
                                <h5>Fonction personnel : {{ personnel.fonction }}</h5><br>
                                <h5>Numéro de téléphone : {{ personnel.telephonePersonnel }}</h5><br>
                                <h5>Spécialiste : {{ personnel.specialite }}</h5><br>
                                <h5>Numéro d'ordre : {{ personnel.numOrdre }}</h5><br>
                                <h5>Date de création : {{ personnel.dateCreation|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}

templates/patient/details_signal.html.twig
{% extends 'patient_template.html.twig' %}

{% block title %} AlloDocteur - Details Signal {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Signal</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Auteur : {{ signal.patient }}</h5><br>
                                <h5>Docteur : {{ signal.personnel }}</h5><br>
                                <h5>Observation : {{ signal.observation }}</h5><br>
                                <h5>Date de création : {{ signal.dateSignal|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}

templates/patient/dossier.html.twig
{% extends 'patient_template.html.twig' %}

{% block title %} AlloDocteur - Dossiers {% endblock %}

{% block body %}

  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Liste des dossiers médicaux</h4>
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                <tr>
                  <th>Numero</th>
                  <th>Patient</th>
                  <th>Description</th>
                  <th>Date creation</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for dossier in dossiers %}
                  <tr>
                    <td>{{ dossier.numero }}</td>
                    <td>{{ dossier.patient }}</td>
                    <td>{{ dossier.descriptionDossier }}</td>
                    <td>{{ dossier.dateCreation|date('Y-m-d') }}</td>
                    <td>
                      <a href="{{ path("dossier_detail", {id: dossier.id}) }}" class="btn btn-primary">Voir</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/patient/examens.html.twig
{% extends 'patient_template.html.twig' %}

{% block title %} AlloDocteur - Examens {% endblock %}

{% block body %}

  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Liste de tous les examens</h4>
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                <tr>
                  <th>Nom examen</th>
                  <th>Description examen</th>
                  <th>Patient</th>
                  <th>Personnel</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for examen in examens %}
                  <tr>
                    <td>{{ examen.nomExamen }}</td>
                    <td>{{ examen.descriptionExamen }}</td>
                    <td>{{ examen.patient }}</td>
                    <td>{{ examen.personnel }}</td>
                    <td>
                      <a href="{{ path("examen_details", {id: examen.id}) }}" class="btn btn-primary">Voir</a>
                      <a href="{{ path("editer_examen", {id: examen.id}) }}" class="btn btn-primary">Modifier</a>
                      <a href="{{ path("delete_examen", {id: examen.id}) }}" class="btn btn-primary">Supprimer</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/patient/profil.html.twig
{% extends 'patient_template.html.twig' %}

{% block title %} AlloDocteur - Profil {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Mon Profil</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview"> 
                    <div class="row">
                      <div class="col-sm-12">
                        <div class="statistics-details d-flex align-items-center justify-content-between">
                          <div>
                            <p class="statistics-title">Mes Examens</p>
                            <h3 class="rate-percentage">{{ examen }}</h3>
                          </div>
                          <div>
                            <p class="statistics-title">Mes Diagnostics</p>
                            <h3 class="rate-percentage">{{ diagnostic }}</h3>
                          </div>
                          <div>
                            <p class="statistics-title">Mes Ordonnances</p>
                            <h3 class="rate-percentage">{{ ordonnance }}</h3>
                          </div>
                          <div class="d-none d-md-block">
                            <p class="statistics-title">Mes Signals</p>
                            <h3 class="rate-percentage">{{ signal }}</h3>
                          </div>
                        </div>
                      </div>
                    </div> 
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Nom : {{ patient[0].nomPatient  }}</h5><br>
                                <h5>Post-Nom :{{ patient[0].postnomPatient }}</h5><br>
                                <h5>Prénom : {{ patient[0].prenomPatient }}</h5><br>
                                <h5>Adresse Email : {{ patient[0].email }}</h5><br>
                                <h5>Numéro Téléphone : {{ patient[0].telephone }}</h5><br>
                                <h5>Age : {{ patient[0].age }}</h5><br>
                                <h5>Matricule : {{ patient[0].matricule }}</h5><br>
                                <h5>Médecin Traitant : {{ patient[0].personnel }}</h5><br>
                                <h5>Date de création : {{ patient[0].dateCreation|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}