src/Entity/Examen.php
<?php

namespace App\Entity;

use App\Repository\ExamenRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExamenRepository::class)]
class Examen
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_examen = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_examen = null;

    #[ORM\ManyToOne(inversedBy: 'examens')]
    private ?Personnel $personnel = null;

    #[ORM\ManyToOne(inversedBy: 'examens')]
    private ?Patient $patient = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_examen = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomExamen(): ?string
    {
        return $this->nom_examen;
    }

    public function setNomExamen(string $nom_examen): static
    {
        $this->nom_examen = $nom_examen;

        return $this;
    }

    public function getDescriptionExamen(): ?string
    {
        return $this->description_examen;
    }

    public function setDescriptionExamen(string $description_examen): static
    {
        $this->description_examen = $description_examen;

        return $this;
    }

    public function getPersonnel(): ?Personnel
    {
        return $this->personnel;
    }

    public function setPersonnel(?Personnel $personnel): static
    {
        $this->personnel = $personnel;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getDateExamen(): ?\DateTimeInterface
    {
        return $this->date_examen;
    }

    public function setDateExamen(\DateTimeInterface $date_examen): static
    {
        $this->date_examen = $date_examen;

        return $this;
    }
}

src/Entity/Fiche.php
<?php

namespace App\Entity;

use App\Repository\FicheRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FicheRepository::class)]
class Fiche
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'fiches')]
    private ?Dossier $dossier = null;

    #[ORM\Column(length: 255)]
    private ?string $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_patient = null;

    #[ORM\Column(length: 255)]
    private ?string $date_entre = null;

    #[ORM\Column(length: 255)]
    private ?string $date_sortie = null;

    #[ORM\ManyToOne(inversedBy: 'fiches')]
    private ?Patient $patient = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_conjoint = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $service = null;

    #[ORM\ManyToOne(inversedBy: 'fiches')]
    private ?Personnel $personnel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $observation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDossier(): ?Dossier
    {
        return $this->dossier;
    }

    public function setDossier(?Dossier $dossier): static
    {
        $this->dossier = $dossier;

        return $this;
    }

    public function getDateNaissance(): ?string
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(string $date_naissance): static
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getAdressePatient(): ?string
    {
        return $this->adresse_patient;
    }

    public function setAdressePatient(string $adresse_patient): static
    {
        $this->adresse_patient = $adresse_patient;

        return $this;
    }

    public function getDateEntre(): ?string
    {
        return $this->date_entre;
    }

    public function setDateEntre(string $date_entre): static
    {
        $this->date_entre = $date_entre;

        return $this;
    }

    public function getDateSortie(): ?string
    {
        return $this->date_sortie;
    }

    public function setDateSortie(string $date_sortie): static
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getNomConjoint(): ?string
    {
        return $this->nom_conjoint;
    }

    public function setNomConjoint(?string $nom_conjoint): static
    {
        $this->nom_conjoint = $nom_conjoint;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(?string $service): static
    {
        $this->service = $service;

        return $this;
    }

    public function getPersonnel(): ?Personnel
    {
        return $this->personnel;
    }

    public function setPersonnel(?Personnel $personnel): static
    {
        $this->personnel = $personnel;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(string $observation): static
    {
        $this->observation = $observation;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }
}

src/Entity/Personnel.php
<?php

namespace App\Entity;

use App\Repository\PersonnelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: PersonnelRepository::class)]
class Personnel implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_personnel = null;

    #[ORM\Column(length: 255)]
    private ?string $postnom_personnel = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_personnel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_personnel = null;

    #[ORM\Column(length: 255)]
    private ?string $fonction = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone_personnel = null;

    #[ORM\Column(length: 255)]
    private ?string $specialite = null;

    #[ORM\Column(length: 255)]
    private ?string $num_ordre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\OneToMany(mappedBy: 'personnel', targetEntity: Patient::class)]
    private Collection $patients;

    #[ORM\OneToMany(mappedBy: 'personnel', targetEntity: Diagnostic::class)]
    private Collection $diagnostics;

    #[ORM\OneToMany(mappedBy: 'personnel', targetEntity: Examen::class)]
    private Collection $examens;

    #[ORM\OneToMany(mappedBy: 'personnel', targetEntity: Ordonnance::class)]
    private Collection $ordonnances;

    #[ORM\OneToMany(mappedBy: 'personnel', targetEntity: Fiche::class)]
    private Collection $fiches;

    #[ORM\OneToMany(mappedBy: 'personnel', targetEntity: Signalement::class)]
    private Collection $signalements;

    public function __construct()
    {
        $this->patients = new ArrayCollection();
        $this->diagnostics = new ArrayCollection();
        $this->examens = new ArrayCollection();
        $this->signals = new ArrayCollection();
        $this->ordonnances = new ArrayCollection();
        $this->fiches = new ArrayCollection();
        $this->signalements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNomPersonnel(): ?string
    {
        return $this->nom_personnel;
    }

    public function setNomPersonnel(string $nom_personnel): static
    {
        $this->nom_personnel = $nom_personnel;

        return $this;
    }

    public function getPostnomPersonnel(): ?string
    {
        return $this->postnom_personnel;
    }

    public function setPostnomPersonnel(string $postnom_personnel): static
    {
        $this->postnom_personnel = $postnom_personnel;

        return $this;
    }

    public function getPrenomPersonnel(): ?string
    {
        return $this->prenom_personnel;
    }

    public function setPrenomPersonnel(string $prenom_personnel): static
    {
        $this->prenom_personnel = $prenom_personnel;

        return $this;
    }

    public function getDescriptionPersonnel(): ?string
    {
        return $this->description_personnel;
    }

    public function setDescriptionPersonnel(string $description_personnel): static
    {
        $this->description_personnel = $description_personnel;

        return $this;
    }

    public function getFonction(): ?string
    {
        return $this->fonction;
    }

    public function setFonction(string $fonction): static
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getTelephonePersonnel(): ?string
    {
        return $this->telephone_personnel;
    }

    public function setTelephonePersonnel(string $telephone_personnel): static
    {
        $this->telephone_personnel = $telephone_personnel;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(string $specialite): static
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getNumOrdre(): ?string
    {
        return $this->num_ordre;
    }

    public function setNumOrdre(string $num_ordre): static
    {
        $this->num_ordre = $num_ordre;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, Patient>
     */
    public function getPatients(): Collection
    {
        return $this->patients;
    }

    public function addPatient(Patient $patient): static
    {
        if (!$this->patients->contains($patient)) {
            $this->patients->add($patient);
            $patient->setPersonnel($this);
        }

        return $this;
    }

    public function removePatient(Patient $patient): static
    {
        if ($this->patients->removeElement($patient)) {
            // set the owning side to null (unless already changed)
            if ($patient->getPersonnel() === $this) {
                $patient->setPersonnel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Diagnostic>
     */
    public function getDiagnostics(): Collection
    {
        return $this->diagnostics;
    }

    public function addDiagnostic(Diagnostic $diagnostic): static
    {
        if (!$this->diagnostics->contains($diagnostic)) {
            $this->diagnostics->add($diagnostic);
            $diagnostic->setPersonnel($this);
        }

        return $this;
    }

    public function removeDiagnostic(Diagnostic $diagnostic): static
    {
        if ($this->diagnostics->removeElement($diagnostic)) {
            // set the owning side to null (unless already changed)
            if ($diagnostic->getPersonnel() === $this) {
                $diagnostic->setPersonnel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Examen>
     */
    public function getExamens(): Collection
    {
        return $this->examens;
    }

    public function addExamen(Examen $examen): static
    {
        if (!$this->examens->contains($examen)) {
            $this->examens->add($examen);
            $examen->setPersonnel($this);
        }

        return $this;
    }

    public function removeExamen(Examen $examen): static
    {
        if ($this->examens->removeElement($examen)) {
            // set the owning side to null (unless already changed)
            if ($examen->getPersonnel() === $this) {
                $examen->setPersonnel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ordonnance>
     */
    public function getOrdonnances(): Collection
    {
        return $this->ordonnances;
    }

    public function addOrdonnance(Ordonnance $ordonnance): static
    {
        if (!$this->ordonnances->contains($ordonnance)) {
            $this->ordonnances->add($ordonnance);
            $ordonnance->setPersonnel($this);
        }

        return $this;
    }

    public function removeOrdonnance(Ordonnance $ordonnance): static
    {
        if ($this->ordonnances->removeElement($ordonnance)) {
            // set the owning side to null (unless already changed)
            if ($ordonnance->getPersonnel() === $this) {
                $ordonnance->setPersonnel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Fiche>
     */
    public function getFiches(): Collection
    {
        return $this->fiches;
    }

    public function addFich(Fiche $fich): static
    {
        if (!$this->fiches->contains($fich)) {
            $this->fiches->add($fich);
            $fich->setPersonnel($this);
        }

        return $this;
    }

    public function removeFich(Fiche $fich): static
    {
        if ($this->fiches->removeElement($fich)) {
            // set the owning side to null (unless already changed)
            if ($fich->getPersonnel() === $this) {
                $fich->setPersonnel(null);
            }
        }

        return $this;
    }

src/Entity/Signal.php
<?php

namespace App\Entity;

use App\Repository\SignalRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SignalRepository::class)]
class Signal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'signals')]
    private ?Patient $patient = null;

    #[ORM\ManyToOne(inversedBy: 'signals')]
    private ?Personnel $personnel = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $observation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_signal = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getPersonnel(): ?Personnel
    {
        return $this->personnel;
    }

    public function setPersonnel(?Personnel $personnel): static
    {
        $this->personnel = $personnel;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(string $observation): static
    {
        $this->observation = $observation;

        return $this;
    }

    public function getDateSignal(): ?\DateTimeInterface
    {
        return $this->date_signal;
    }

    public function setDateSignal(\DateTimeInterface $date_signal): static
    {
        $this->date_signal = $date_signal;

        return $this;
    }
}

templates/personnel/details_fiche.html.twig
{% extends 'medecin_template.html.twig' %}

{% block title %} AlloDocteur - Details Fiche {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Fiche</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Numéro fiche : Fiche N°{{ fiche.id }}</h5><br>
                                <h5>Dossier : {{ fiche.dossier }}</h5><br>
                                <h5>Nom patient : {{ fiche.patient }}</h5><br>
                                <h5>Date de naissance: {{ fiche.dateNaissance|date('Y-m-d') }}</h5><br>
                                <h5>Date d'entrée: {{ fiche.dateEntre|date('Y-m-d') }}</h5><br>
                                <h5>Date de sortie: {{ fiche.dateSortie|date('Y-m-d') }}</h5><br>
                                <h5>Service : {{ fiche.service }}</h5><br>
                                <h5>Observation : {{ fiche.observation }}</h5><br>
                                <h5>Adresse patient : {{ fiche.adressePatient }}</h5><br>
                                <h5>Date de création : {{ fiche.dateCreation|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}

templates/personnel/details_patient.html.twig
{% extends 'medecin_template.html.twig' %}

{% block title %} AlloDocteur - Détails patient {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Patient {{ patient.nomPatient }}</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Nom patient : {{ patient.nomPatient }}</h5><br>
                                <h5>Post-nom patient : {{ patient.postnomPatient }}</h5><br>
                                <h5>Prenom patient : {{ patient.prenomPatient }}</h5><br>
                                <h5>Description du patient : {{ patient.descriptionPatient }}</h5><br>
                                <h5>Age patient : {{ patient.age }} ans</h5><br>
                                <h5>Numéro de téléphone : {{ patient.telephone }}</h5><br>
                                <h5>Matricule : {{ patient.matricule }}</h5><br>
                                <h5>Médecin traitent : {{ patient.personnel }}</h5><br>
                                <h5>Date de création : {{ patient.dateCreation|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}

templates/personnel/details_personnel.html.twig
{% extends 'medecin_template.html.twig' %}

{% block title %} AlloDocteur - Details Personnel {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Tableau de bord</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Nom personnel : {{ personnel.nomPersonnel }}</h5><br>
                                <h5>Post-nom personnel : {{ personnel.postnomPersonnel }}</h5><br>
                                <h5>Prenom personnel : {{ personnel.prenomPersonnel }}</h5><br>
                                <h5>Description du personnel : {{ personnel.descriptionPersonnel }}</h5><br>
                                <h5>Fonction personnel : {{ personnel.fonction }}</h5><br>
                                <h5>Numéro de téléphone : {{ personnel.telephonePersonnel }}</h5><br>
                                <h5>Spécialiste : {{ personnel.specialite }}</h5><br>
                                <h5>Numéro d'ordre : {{ personnel.numOrdre }}</h5><br>
                                <h5>Date de création : {{ personnel.dateCreation|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}

templates/personnel/examen_details.html.twig
{% extends 'medecin_template.html.twig' %}

{% block title %} AlloDocteur - Details examen {% endblock %}

{% block body %}

      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="dossier" data-bs-toggle="tab" href="#dossier" role="tab" aria-controls="dossier" aria-selected="true">Examens</a>
                    </li>
                  </ul>
                </div>
                <div class="tab-content tab-content-basic">
                  <div class="tab-pane fade show active" id="dossier" role="tabpanel" aria-labelledby="dossier">
                    <div class="row">
                      <div class="col-lg-8 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <h5>Nom du Personnel : {{ examen.personnel }}</h5><br>
                                <h5>Non du Patient : {{ examen.patient }}</h5><br>
                                <h5>Dénomination examen : {{ examen.nomExamen }}</h5><br>
                                <h5>Description examen : {{ examen.descriptionExamen }}</h5><br>
                                <h5>Date de création : {{ examen.dateExamen|date('Y-m-d') }}</h5>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-4 d-flex flex-column">
                        <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <div class="row">
                                  <div class="col-lg-12">
                                    <div class="d-flex justify-content-between align-items-center">
                                      <h4 class="card-title card-title-dash">Mes Taches</h4>
                                      <div class="add-items d-flex mb-0">
                                        <!-- <input type="text" class="form-control todo-list-input" placeholder="What do you need to do today?"> -->
                                        <button class="add btn btn-icons btn-rounded btn-primary todo-list-add-btn text-white me-0 pl-12p"><i class="mdi mdi-plus"></i></button>
                                      </div>
                                    </div>
                                    <div class="list-wrapper">
                                      <ul class="todo-list todo-list-rounded">
                                        <li class="d-block">
                                          <div class="form-check w-100">
                                            <label class="form-check-label">
                                              <input class="checkbox" type="checkbox">Créer les comptes des médecins<i class="input-helper rounded"></i>
                                            </label>
                                          </div>
                                        </li>
                                        <li class="d-block">
                                          <div class="form-check w-100">
                                            <label class="form-check-label">
                                              <input class="checkbox" type="checkbox">Prendre les informations des patients<i class="input-helper rounded"></i>
                                            </label>
                                          </div>
                                        </li>
                                        <li>
                                          <div class="form-check w-100">
                                            <label class="form-check-label">
                                              <input class="checkbox" type="checkbox"> Constituer les dossiers <i class="input-helper rounded"></i>
                                            </label>
                                          </div>
                                        </li>
                                        <li class="border-bottom-0">
                                          <div class="form-check w-100">
                                            <label class="form-check-label">
                                              <input class="checkbox" type="checkbox">Assigner Médecin <i class="input-helper rounded"></i>
                                            </label>
                                          </div>
                                        </li>
                                      </ul>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <!-- partial -->
      </div>
{% endblock %}